### ISSUE TITLE
About the format of input data

### ISSUE THREAD

**Issue by kevin-dong-nai-jia** [NCTU-CSE-Introduction-to-Algorithms/assignment-2-announcement-and-discussion#5]
> The inputs will be multiple numbers that be seperated by space, tab or newline character, and end with a x alphabet, there will be at most 10000 inputs.

I am a bit confused about the description above.

Do you mean that the input consists of several (less than 10000) integers each separated by whitespace characters and ends up with an `x`? Hence, is it possible to enter `65 21 54 x 95 21 35 74 x` as an input?

**Comment by Yi-Tseng** [comment]
No

There will be only one 'x' in one test case.
